; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:disco_f746ng]
platform = ststm32
board = disco_f746ng
framework = arduino
upload_protocol = stlink
monitor_speed = 115200

# Zephyr specific configurations
board_build.zephyr.config = 
    CONFIG_SERIAL=y
    CONFIG_CONSOLE=y
    CONFIG_UART_CONSOLE=y
    CONFIG_GPIO=y
    CONFIG_LOG=y

build_flags = 
    -I include
    -I src 